"""migration default

Revision ID: e9b6dfbb08a3
Revises: 
Create Date: 2025-05-27 10:41:08.085913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b6dfbb08a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabricante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmacia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmaceutico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('licenca', sa.String(length=50), nullable=False),
    sa.Column('farmacia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmacia_id'], ['farmacia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licenca')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('numeracao_original', sa.Integer(), nullable=True),
    sa.Column('grupo', sa.String(length=50), nullable=False),
    sa.Column('fabricante_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_embalagem', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('preco_compra', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=13), nullable=False),
    sa.ForeignKeyConstraint(['fabricante_id'], ['fabricante.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('farmacia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmacia_id'], ['farmacia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_farmacia_id'), ['farmacia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmacia_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmacia_id'], ['farmacia.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_log')
    op.drop_table('estoque')
    op.drop_table('vendedor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_farmacia_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('produto')
    op.drop_table('farmaceutico')
    op.drop_table('fornecedor')
    op.drop_table('farmacia')
    op.drop_table('fabricante')
    # ### end Alembic commands ###
